import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';
import { buildDocEndpoints } from './yapi-api/doc.endpoints';
import { buildInterfaceEndpoints } from './yapi-api/interface.endpoints';
import { buildProjectSpecEndpoints } from './yapi-api/project-spec.endpoints';
import { apiBaseUrl, tagTypes } from './yapi-api/shared';
import { buildUserGroupEndpoints } from './yapi-api/user-group.endpoints';

export const yapiApi = createApi({
  reducerPath: 'yapiApi',
  baseQuery: fetchBaseQuery({
    baseUrl: apiBaseUrl,
    credentials: 'include'
  }),
  tagTypes,
  endpoints: builder => ({
    ...buildUserGroupEndpoints(builder),
    ...buildProjectSpecEndpoints(builder),
    ...buildDocEndpoints(builder),
    ...buildInterfaceEndpoints(builder)
  })
});

export const {
  useLoginMutation,
  useRegisterUserMutation,
  useLoginByTokenMutation,
  useGetUserStatusQuery,
  useGetUserListQuery,
  useFindUserQuery,
  useLazyFindUserQuery,
  useUpdateUserMutation,
  useDeleteUserMutation,
  useUpdateStudyMutation,
  useChangePasswordMutation,
  useSearchUsersQuery,
  useLazySearchUsersQuery,
  useGetUserProjectContextQuery,
  useLazyGetUserProjectContextQuery,
  useUploadAvatarMutation,
  useLogoutMutation,
  useGetGroupListQuery,
  useGetMyGroupQuery,
  useGetGroupQuery,
  useAddGroupMutation,
  useUpdateGroupMutation,
  useDelGroupMutation,
  useGetGroupMemberListQuery,
  useAddGroupMemberMutation,
  useDelGroupMemberMutation,
  useChangeGroupMemberRoleMutation,
  useGetProjectListQuery,
  useCheckProjectNameQuery,
  useLazyCheckProjectNameQuery,
  useAddProjectMutation,
  useCopyProjectMutation,
  useDelProjectMutation,
  useGetFollowListQuery,
  useAddFollowMutation,
  useDelFollowMutation,
  useUpdateProjectMutation,
  useGetProjectEnvQuery,
  useUpdateProjectEnvMutation,
  useUpdateProjectTagMutation,
  useGenerateProjectApiMarkdownMutation,
  useAddProjectMemberMutation,
  useGetProjectMemberListQuery,
  useLazyGetProjectMemberListQuery,
  useDelProjectMemberMutation,
  useChangeProjectMemberRoleMutation,
  useChangeProjectMemberEmailNoticeMutation,
  useUpsetProjectMutation,
  useGetProjectQuery,
  useGetProjectTokenQuery,
  useUpdateProjectTokenMutation,
  useSearchProjectQuery,
  useLazySearchProjectQuery,
  useFetchSwaggerByUrlQuery,
  useLazyFetchSwaggerByUrlQuery,
  useImportSpecMutation,
  useGetImportTaskQuery,
  useListImportTasksQuery,
  useExportSpecMutation,
  useGetDocTreeQuery,
  useAddDocNodeMutation,
  useUpdateDocNodeMutation,
  useMoveDocNodeMutation,
  useDeleteDocNodeMutation,
  useGetInterfaceTreeQuery,
  useLazyGetInterfaceTreeQuery,
  useGetInterfaceTreeNodeQuery,
  useLazyGetInterfaceTreeNodeQuery,
  useGetListMenuQuery,
  useGetInterfaceListQuery,
  useGetInterfaceQuery,
  useLazyGetInterfaceQuery,
  useAddInterfaceMutation,
  useSaveInterfaceMutation,
  useUpdateInterfaceMutation,
  useDelInterfaceMutation,
  useGetCatMenuQuery,
  useAddInterfaceCatMutation,
  useUpdateInterfaceCatMutation,
  useDelInterfaceCatMutation,
  useUpInterfaceIndexMutation,
  useUpInterfaceCatIndexMutation,
  useGetColListQuery,
  useAddColMutation,
  useUpColCompatMutation,
  useDelColMutation,
  useGetColCaseListQuery,
  useGetColCaseEnvListQuery,
  useGetColCaseListByVarParamsQuery,
  useAddColCaseMutation,
  useAddColCaseListMutation,
  useCloneColCaseListMutation,
  useUpColCaseMutation,
  useGetColCaseQuery,
  useLazyGetColCaseQuery,
  useDelColCaseMutation,
  useUpColCaseIndexMutation,
  useUpColIndexMutation,
  useRunColCaseScriptMutation,
  useGetLogListQuery,
  useInterUploadMutation
} = yapiApi;
